# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administratorwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdministratorWindow(object):
    def setupUi(self, AdministratorWindow):
        AdministratorWindow.setObjectName("AdministratorWindow")
        AdministratorWindow.resize(1090, 766)
        AdministratorWindow.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0.502, y1:0.0611111, x2:0.527155, y2:1, stop:0 rgba(0, 255, 104, 255), stop:0.971014 rgba(123, 255, 165, 255))\n"
"")
        self.centralwidget = QtWidgets.QWidget(AdministratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cargopushButtnon = QtWidgets.QPushButton(self.centralwidget)
        self.cargopushButtnon.setGeometry(QtCore.QRect(550, 280, 221, 201))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.cargopushButtnon.setFont(font)
        self.cargopushButtnon.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.502, y2:0.994318, stop:0.502415 rgba(85, 255, 127, 255), stop:1 rgba(155, 255, 188, 255));")
        self.cargopushButtnon.setObjectName("cargopushButtnon")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 210, 441, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.staffpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.staffpushButton.setGeometry(QtCore.QRect(310, 280, 221, 201))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.staffpushButton.setFont(font)
        self.staffpushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.502, y2:0.994318, stop:0.502415 rgba(85, 255, 127, 255), stop:1 rgba(155, 255, 188, 255));")
        self.staffpushButton.setObjectName("staffpushButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 500, 461, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(85, 0, 0);\n"
"background-color: rgb(129, 255, 154);")
        self.pushButton.setObjectName("pushButton")
        AdministratorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdministratorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 25))
        self.menubar.setObjectName("menubar")
        AdministratorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdministratorWindow)
        self.statusbar.setObjectName("statusbar")
        AdministratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdministratorWindow)
        QtCore.QMetaObject.connectSlotsByName(AdministratorWindow)

    def retranslateUi(self, AdministratorWindow):
        _translate = QtCore.QCoreApplication.translate
        AdministratorWindow.setWindowTitle(_translate("AdministratorWindow", "MainWindow"))
        self.cargopushButtnon.setText(_translate("AdministratorWindow", "货物管理"))
        self.label_2.setText(_translate("AdministratorWindow", "选项"))
        self.staffpushButton.setText(_translate("AdministratorWindow", "员工管理"))
        self.pushButton.setText(_translate("AdministratorWindow", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdministratorWindow = QtWidgets.QMainWindow()
    ui = Ui_AdministratorWindow()
    ui.setupUi(AdministratorWindow)
    AdministratorWindow.show()
    sys.exit(app.exec_())
