# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cargowindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 766)
        MainWindow.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0.502, y1:0.0611111, x2:0.527155, y2:1, stop:0 rgba(0, 255, 104, 255), stop:0.971014 rgba(123, 255, 165, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 230, 431, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.productNameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(15)
        self.productNameEdit.setFont(font)
        self.productNameEdit.setObjectName("productNameEdit")
        self.gridLayout.addWidget(self.productNameEdit, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.amountLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(15)
        self.amountLineEdit.setFont(font)
        self.amountLineEdit.setObjectName("amountLineEdit")
        self.gridLayout.addWidget(self.amountLineEdit, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.priceLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(15)
        self.priceLineEdit.setFont(font)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.gridLayout.addWidget(self.priceLineEdit, 2, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)
        self.returnButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(14)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);")
        self.returnButton.setObjectName("returnButton")
        self.gridLayout.addWidget(self.returnButton, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "商品名称"))
        self.productNameEdit.setStyleSheet(_translate("MainWindow", "background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);"))
        self.label.setText(_translate("MainWindow", "商品库存"))
        self.amountLineEdit.setStyleSheet(_translate("MainWindow", "background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);"))
        self.label_2.setText(_translate("MainWindow", "商品价格"))
        self.priceLineEdit.setStyleSheet(_translate("MainWindow", "background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.returnButton.setText(_translate("MainWindow", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
