# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffmanagementwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StaffmanagementWindow(object):
    def setupUi(self, StaffmanagementWindow):
        StaffmanagementWindow.setObjectName("StaffmanagementWindow")
        StaffmanagementWindow.resize(1090, 700)
        StaffmanagementWindow.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0.502, y1:0.0611111, x2:0.527155, y2:1, stop:0 rgba(0, 255, 104, 255), stop:0.971014 rgba(123, 255, 165, 255))\n"
"")
        self.centralwidget = QtWidgets.QWidget(StaffmanagementWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 0, 1021, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.deletepushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.deletepushButton.setFont(font)
        self.deletepushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.deletepushButton.setObjectName("deletepushButton")
        self.gridLayout.addWidget(self.deletepushButton, 1, 1, 1, 1)
        self.addpushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.addpushButton.setFont(font)
        self.addpushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addpushButton.setObjectName("addpushButton")
        self.gridLayout.addWidget(self.addpushButton, 0, 1, 1, 1)
        self.returnpushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.returnpushButton.setFont(font)
        self.returnpushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.returnpushButton.setObjectName("returnpushButton")
        self.gridLayout.addWidget(self.returnpushButton, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 3, 1)
        StaffmanagementWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffmanagementWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 25))
        self.menubar.setObjectName("menubar")
        StaffmanagementWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffmanagementWindow)
        self.statusbar.setObjectName("statusbar")
        StaffmanagementWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StaffmanagementWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffmanagementWindow)

    def retranslateUi(self, StaffmanagementWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffmanagementWindow.setWindowTitle(_translate("StaffmanagementWindow", "MainWindow"))
        self.deletepushButton.setText(_translate("StaffmanagementWindow", "删除"))
        self.addpushButton.setText(_translate("StaffmanagementWindow", "增加"))
        self.returnpushButton.setText(_translate("StaffmanagementWindow", "返回主界面"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StaffmanagementWindow = QtWidgets.QMainWindow()
    ui = Ui_StaffmanagementWindow()
    ui.setupUi(StaffmanagementWindow)
    StaffmanagementWindow.show()
    sys.exit(app.exec_())
