# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StaffWindow(object):
    def setupUi(self, StaffWindow):
        StaffWindow.setObjectName("StaffWindow")
        StaffWindow.resize(1090, 766)
        font = QtGui.QFont()
        font.setPointSize(10)
        StaffWindow.setFont(font)
        StaffWindow.setStyleSheet("background-color:\n"
"qlineargradient(spread:pad, x1:0.502, y1:0.0611111, x2:0.527155, y2:1, stop:0 rgba(0, 255, 104, 255), stop:0.971014 rgba(123, 255, 165, 255))\n"
"")
        self.centralwidget = QtWidgets.QWidget(StaffWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inquireButtnon = QtWidgets.QPushButton(self.centralwidget)
        self.inquireButtnon.setGeometry(QtCore.QRect(560, 260, 221, 201))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.inquireButtnon.setFont(font)
        self.inquireButtnon.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.502, y2:0.994318, stop:0.502415 rgba(85, 255, 127, 255), stop:1 rgba(155, 255, 188, 255));")
        self.inquireButtnon.setObjectName("inquireButtnon")
        self.shoppingButton = QtWidgets.QPushButton(self.centralwidget)
        self.shoppingButton.setGeometry(QtCore.QRect(320, 260, 221, 201))
        font = QtGui.QFont()
        font.setFamily("思源宋体 CN")
        font.setPointSize(15)
        self.shoppingButton.setFont(font)
        self.shoppingButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.502, y2:0.994318, stop:0.502415 rgba(85, 255, 127, 255), stop:1 rgba(155, 255, 188, 255));")
        self.shoppingButton.setObjectName("shoppingButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 190, 441, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"border-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 500, 461, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(85, 0, 0);\n"
"background-color: rgb(129, 255, 154);")
        self.pushButton.setObjectName("pushButton")
        StaffWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 25))
        self.menubar.setObjectName("menubar")
        StaffWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffWindow)
        self.statusbar.setObjectName("statusbar")
        StaffWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StaffWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffWindow)

    def retranslateUi(self, StaffWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffWindow.setWindowTitle(_translate("StaffWindow", "MainWindow"))
        self.inquireButtnon.setText(_translate("StaffWindow", "货物查询"))
        self.shoppingButton.setText(_translate("StaffWindow", "购物"))
        self.label.setText(_translate("StaffWindow", "选项"))
        self.pushButton.setText(_translate("StaffWindow", "返回"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StaffWindow = QtWidgets.QMainWindow()
    ui = Ui_StaffWindow()
    ui.setupUi(StaffWindow)
    StaffWindow.show()
    sys.exit(app.exec_())
